server:
  port: 8088
  tomcat:
    uri-encoding: utf-8
  max-http-header-size: 80KB
spring:
  #数据库连接配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/food?useUnicode=true&characterEncoding=utf-8&autoReconnrct=true&useSSL=false
    username: root
    password: root1234
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DateSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lqkun.food.pojo

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  # 通用 Mapper 配置
  mapper:
    mappers: com.lqkun.food.my.mapper.MyMapper
    # 在进行数据库操作的的时候，判断表达式 username != null, 是否追加 username != ''
    not-empty: false
    identity: MYSQL
